version: 2.1

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:8.14.0

commands:
  prep_env:
    description: "Prepares environment with cache"
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          name: Restore node_modules cache
          key: website-{{ checksum "yarn.lock" }}-{{ .Branch }}
  save_env_cache:
    description: "Saves environment cache"
    steps:
      - save_cache:
          name: Save node_modules cache
          key: websote-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules/

jobs:
  node_modules:
    <<: *docker_defaults
    working_directory: ~/repo
    steps:
      - prep_env
      - run: yarn install --frozen-lockfile
      - save_env_cache
  website:
    <<: *docker_defaults
    working_directory: ~/repo/website
    steps:
      - prep_env
      - run: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - build/
  deploy_website:
    <<: *docker_defaults
    working_directory: ~/repo/website
    steps:
      - prep_env
      - attach_workspace:
          at: ./
      - add_ssh_keys:
          fingerprints:
            - "31:a5:c5:3d:78:b9:79:1d:2f:4b:59:fd:e1:89:21:dc"
      - run:
          name: Setup git user and deploy website
          command: |
            git config --global user.email "circleci-all-contributors-website@users.noreply.github.com"
            git config --global user.name "CircleCI All Contributors Website"
            CUSTOM_COMMIT_MESSAGE="[skip ci]" USE_SSH=true yarn publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - node_modules
      - website:
          requires:
            - node_modules
      - deploy_website:
          requires:
            - website
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
